name: CICD

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    types: [ opened, synchronize, edited ]

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml
  CD:
    needs: [CI]
    uses: ./.github/workflows/cd-workflow.yml
